# Generated by Django 4.2.7 on 2023-12-30 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(verbose_name='Nickname'),
        ),
    ]
