# Generated by Django 4.2.7 on 2023-12-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0003_alter_reviews_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='view_count',
            field=models.IntegerField(auto_created=True, default=0, verbose_name='Количество просмотров'),
        ),
    ]
