# Generated by Django 4.2.7 on 2024-01-02 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0004_alter_reviews_view_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='view_count',
            new_name='views_count',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='slug',
            field=models.SlugField(max_length=255, verbose_name='Nickname'),
        ),
    ]
