# Generated by Django 4.2.7 on 2024-01-03 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews_app', '0006_alter_reviews_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='reviews/', verbose_name='Изображение'),
        ),
    ]
